//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTypeScript.ProxyCreator.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AngularJsProxyTsTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AngularJsProxyTsTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTypeScript.ProxyCreator.Templates.AngularJsProxyTsTemplates", typeof(AngularJsProxyTsTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Achtung diese Datei wurde automatisch erstellt,
        /////bitte nehmen Sie keine Änderungen daran vor, diese werden
        /////beim nächsten Erstellen wieder überschrieben.
        /////Erstellt am {0} um {1} von {2}..
        /// </summary>
        internal static string AutomaticlyCreated {
            get {
                return ResourceManager.GetString("AutomaticlyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}) : void  {{
        ///    this.$http.{2};
        ///}}.
        /// </summary>
        internal static string FunctionDefnitionNoReturnType {
            get {
                return ResourceManager.GetString("FunctionDefnitionNoReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}) : ng.IPromise&lt;{2}&gt; {{
        ///    return this.$http.{3}.then((response: ng.IHttpPromiseCallbackArg&lt;{2}&gt;) : {2} 
        ///	=&gt; {{ return response.data; }} );
        ///}}.
        /// </summary>
        internal static string FunctionDefnitionWithReturnType {
            get {
                return ResourceManager.GetString("FunctionDefnitionWithReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module App.Services {{
        ///
        /// export interface I{0} {{
        ///	{1}
        /// }}
        ///
        ///  export class {0} implements I{0} {{
        ///          static $inject = [&apos;$http&apos;];
        ///          constructor(private $http: ng.IHttpService) {{ }}
        ///
        ///		{2}
        ///
        ///
        ///         //#region Angular Module Definition
        ///        private static _module: ng.IModule;
        ///        public static get module(): ng.IModule {{
        ///            if (this._module) {{
        ///                return this._module;
        ///            }}
        ///            this._module = angular.module(&apos;{3}&apos;, []);
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModuleTemplate {
            get {
                return ResourceManager.GetString("ModuleTemplate", resourceCulture);
            }
        }
    }
}
