//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTypeScript.ProxyCreator.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AngularProxyJsTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AngularProxyJsTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcTypeScript.ProxyCreator.Templates.AngularProxyJsTemplates", typeof(AngularProxyJsTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Achtung diese Datei wurde automatisch erstellt,
        /////bitte nehmen Sie keine Änderungen daran vor, diese werden
        /////beim nächsten Erstellen wieder überschrieben.
        /////Erstellt am {0} um {1} von {2}..
        /// </summary>
        public static string AutomaticlyCreated {
            get {
                return ResourceManager.GetString("AutomaticlyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.prototype.{1} = function ({2}) {{
        ///    return this.http.{3}.then(function (result) {{
        ///        return result.data;
        ///    }});
        ///}};.
        /// </summary>
        public static string BasicSuccessServerCall {
            get {
                return ResourceManager.GetString("BasicSuccessServerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular.module(&quot;{0}&quot;, [])
        ///    .service(&quot;{0}&quot;, [&apos;$http&apos;, &apos;$log&apos;, {0}]);.
        /// </summary>
        public static string ModuleDefinition {
            get {
                return ResourceManager.GetString("ModuleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function {0}($http, $log) {{ 
        ///      this.log = $log, this.http = $http; 
        ///}};.
        /// </summary>
        public static string ServerFunctionDefinition {
            get {
                return ResourceManager.GetString("ServerFunctionDefinition", resourceCulture);
            }
        }
    }
}
